import io
import os
from datetime import datetime, timezone
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from app.database import SessionLocal
from app.models.finding import Finding
from app.models.target import Target

router = APIRouter()

SEVERITY_COLOR = {
    "critical": "#dc2626",
    "high": "#ea580c",
    "medium": "#d97706",
    "low": "#16a34a",
    "info": "#2563eb",
}


def _build_html(finding: Finding, target: Target | None) -> str:
    severity = (finding.severity or "info").lower()
    color = SEVERITY_COLOR.get(severity, "#6b7280")
    vuln_class = getattr(finding, "vulnerability_class", None) or "Unknown"
    program = target.name if target else "Unknown Program"
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    evidence_html = ""
    if finding.evidence:
        evidence_html = f"<pre style='background:#f3f4f6;padding:12px;border-radius:6px;overflow-x:auto;font-size:12px;'>{finding.evidence}</pre>"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 0; padding: 40px; color: #1f2937; background: #fff; }}
  h1 {{ font-size: 24px; color: #111827; margin-bottom: 4px; }}
  .meta {{ color: #6b7280; font-size: 13px; margin-bottom: 32px; }}
  .badge {{ display: inline-block; padding: 4px 12px; border-radius: 9999px; color: #fff;
             background: {color}; font-weight: 700; font-size: 13px; text-transform: uppercase; }}
  .section {{ margin-top: 28px; }}
  .section h2 {{ font-size: 16px; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px; margin-bottom: 12px; color: #374151; }}
  p {{ line-height: 1.7; margin: 0 0 10px; }}
  pre {{ background:#f3f4f6; padding:12px; border-radius:6px; font-size:12px; overflow-x:auto; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  th {{ background: #f9fafb; text-align: left; padding: 8px 12px; border: 1px solid #e5e7eb; }}
  td {{ padding: 8px 12px; border: 1px solid #e5e7eb; }}
  .footer {{ margin-top: 48px; font-size: 11px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 16px; }}
</style>
</head>
<body>
  <h1>Bug Report: {finding.title}</h1>
  <p class="meta">Program: <strong>{program}</strong> &nbsp;|&nbsp; Date: {date_str} &nbsp;|&nbsp; ID: FIND-{finding.id:04d}</p>
  <span class="badge">{severity}</span>

  <div class="section">
    <h2>Summary</h2>
    <table>
      <tr><th>Field</th><th>Value</th></tr>
      <tr><td>Vulnerability Class</td><td>{vuln_class}</td></tr>
      <tr><td>Severity</td><td>{severity.upper()}</td></tr>
      <tr><td>Status</td><td>Open</td></tr>
      <tr><td>Target</td><td>{program}</td></tr>
      <tr><td>Reported</td><td>{date_str}</td></tr>
    </table>
  </div>

  <div class="section">
    <h2>Description</h2>
    <p>{finding.description or 'No description provided.'}</p>
  </div>

  <div class="section">
    <h2>Reproduction Steps</h2>
    <ol>
      <li>Authenticate as a normal user account</li>
      <li>Navigate to the affected endpoint</li>
      <li>Perform the action described above and observe the vulnerability</li>
      <li>Confirm the security impact</li>
    </ol>
  </div>

  <div class="section">
    <h2>Evidence</h2>
    {evidence_html if evidence_html else '<p>No evidence attached.</p>'}
  </div>

  <div class="section">
    <h2>Impact</h2>
    <p>This vulnerability may allow an attacker to compromise user data, bypass authentication, or affect application integrity depending on the exploitation scenario.</p>
  </div>

  <div class="section">
    <h2>Remediation</h2>
    <ul>
      <li>Implement proper server-side authorization checks on every request</li>
      <li>Validate and sanitize all user-supplied input</li>
      <li>Apply the principle of least privilege</li>
      <li>Conduct regular security code reviews and penetration testing</li>
    </ul>
  </div>

  <div class="footer">
    Generated by BugHunterLab &mdash; {date_str}
  </div>
</body>
</html>"""


def _build_markdown(finding: Finding, target: Target | None) -> str:
    program = target.name if target else "Unknown Program"
    vuln_class = getattr(finding, "vulnerability_class", None) or "Unknown"
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    return f"""# Bug Report: {finding.title}

**Program:** {program}  
**Severity:** {(finding.severity or "").upper()}  
**Vulnerability Class:** {vuln_class}  
**Status:** Open  
**Date:** {date_str}  
**ID:** FIND-{finding.id:04d}

---

## Description

{finding.description or "No description provided."}

## Reproduction Steps

1. Authenticate as a normal user
2. Navigate to the affected endpoint
3. Observe the vulnerability
4. Confirm the security impact

## Evidence

{finding.evidence or "No evidence attached."}

## Impact

This vulnerability may allow an attacker to compromise user data, bypass authentication,
or affect application integrity depending on the exploitation scenario.

## Remediation

- Implement proper server-side authorization on every request
- Validate and sanitize all user-supplied input
- Apply the principle of least privilege
- Conduct regular security code reviews and penetration testing

---
*Generated by BugHunterLab on {date_str}*
"""


@router.get("/{finding_id}")
def get_report(finding_id: int):
    """Return report data (markdown + preview HTML)."""
    db = SessionLocal()
    try:
        finding = db.query(Finding).filter(Finding.id == finding_id).first()
        if not finding:
            raise HTTPException(status_code=404, detail="Finding not found")
        target = db.query(Target).filter(Target.id == finding.target_id).first()
        md = _build_markdown(finding, target)
        html_preview = _build_html(finding, target)
        return {
            "title": finding.title,
            "markdown": md,
            "html_preview": html_preview,
            "plain_text": f"FIND-{finding.id:04d} | {finding.severity.upper()} | {finding.title}",
            "pdf_url": f"/api/report/{finding_id}/pdf",
        }
    finally:
        db.close()


@router.get("/{finding_id}/pdf")
def download_report_pdf(finding_id: int):
    """Generate and stream a PDF report for a finding."""
    db = SessionLocal()
    try:
        finding = db.query(Finding).filter(Finding.id == finding_id).first()
        if not finding:
            raise HTTPException(status_code=404, detail="Finding not found")
        target = db.query(Target).filter(Target.id == finding.target_id).first()
        html_content = _build_html(finding, target)

        try:
            from weasyprint import HTML as WP
            pdf_bytes = WP(string=html_content).write_pdf()
        except ImportError:
            # WeasyPrint not installed — return HTML as fallback with .html extension
            return StreamingResponse(
                io.BytesIO(html_content.encode()),
                media_type="text/html",
                headers={"Content-Disposition": f"attachment; filename=report-{finding_id}.html"},
            )

        return StreamingResponse(
            io.BytesIO(pdf_bytes),
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename=report-{finding_id}.pdf"},
        )
    finally:
        db.close()
